---
openapi: 3.0.1
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
info:
  title: Weather API
  version: v1
components:
  schemas:
    HealthCheck:
      show:
        response:
          body:
            type: object
            properties:
              status:
                type: string
                example: ok
paths:
  "/health":
    get:
      summary: show health_check
      responses:
        '200':
          description: show API health
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheck/show/response/body"
